IMDB:
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: at-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEATMAIN: Atza|IwEBIF_hMCU4fWyudboyfejNgW7DX1JPAMptuP7aGqZH6YhoFb4dMLwGURMpJYO7LWzmT62FHXmp_f72K0jobhAmQZWL_oo6hJaxkNBclC9g-QD5YiQ7HZrEtV5KIiIcb6GP_agxh9Y4RwGE_kM_86RHM0SKOmKgbB70AuvDsZlwi7vWZv7VDpaTlOTC45WlWgtGxenYERtrUBMRjYfadD2yZ0WvWY3RoMSPec8V4x6VbEoe6Q
    # Log into your IMDb account from a web browser, inspect the cookies and retrieve the value of cookie:
    # name: ubid-main | domain: .imdb.com
    # You need to replace this value with your own, the default value is for illustrative purposes only
    COOKIEUBIDMAIN: 132-4174122-8022759
    # Array of IMDb lists that you would like synced to Trakt
    # If this array is empty, all IMDb lists will be synced to Trakt
    # Keep in mind the maximum number of lists you can have in Trakt: https://twitter.com/trakt/status/1536751362943332352
    # In order to get the ID of an IMDb list, open it from a browser - the ID is in the URL with format ls#########
    LISTS:
        - ls000000000
        - ls111111111
SYNC:
    # Sync mode to be used when running the application
    # The value must be one of the following:
    #   full     - sync all IMDb items by adding, deleting and updating Trakt resources
    #   add-only - sync only newly added IMDb items to Trakt
    #   dry-run  - identify what IMDb items would be added, deleted or updated on Trakt
    MODE: full
    # Whether to skip history sync or not. If set to true, history sync will be skipped
    # IMDb doesn't offer functionality similar to Trakt history, hence why there can't be a direct mapping between them
    # The syncer will assume you have watched an item if you've submitted a rating for it
    # If the above is satisfied and your history for this item is empty, then a new history entry will be added...
    SKIPHISTORY: true
TRAKT:
    # Trakt app client ID
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTID: 997bd8fdc667a631c08feac1ca1cd3ff4fc09181653f34fb812d77e6ebdd321d
    # Trakt app client secret
    # You need to replace this value with your own, the default value is for illustrative purposes only
    CLIENTSECRET: f29e99f8fe172aa5ab7025b1d0514404f3dd72e7adf9df91c7f677945ffe9415
    # Trakt account email address (not to be confused with username)
    # You need to replace this value with your own, the default value is for illustrative purposes only
    EMAIL: skrivskithar@gmail.com
    # Trakt account password
    # You need to replace this value with your own, the default value is for illustrative purposes only
    PASSWORD: }TRiC6~G6GC:Y'C
